### ISSUE TITLE
Make timestamp format for monitoring adjustable

### ISSUE THREAD

**Issue by daFritz84** [calimero-project/calimero-gui#2]
Right now the timestamp format for the monitoring is fixed (or probably hidden away in the simplelogger.properties) to HH:MM:SS. However this is not beneficial for logging for several days where the resulting csv has then to be postprocessed.

I propose making the timestamps adjustable in some form. Either by a property in a configuration file or, probably more user-friendly, even by means of the GUI .

See also screenshot below:
![screenshot](https://user-images.githubusercontent.com/3084809/40483703-220d98d6-5f59-11e8-97e8-2965d179d067.PNG)

**Comment by bmalinowsky** [comment]
I see... would it make sense to have an additional column left of time with the date? The export would then also consist of two columns [..., date, time, ...]. Or everything in the same table column.

I guess it would be nice if the gui remembered a modified user setting between executions, so it has to go into a config file anyway.

**Comment by daFritz84** [comment]
I think as long as the date is somehow included in the resulting csv either option is fine. Putting in a date column would additionally allow for a more fine grained filtering mechanism, which is probably another feature worth having.

Regarding config files: Probably [cfg4j](http://www.cfg4j.org) is a viable option. 

BTW: I'm happy to help and submit a pull request once it is decided how such a feature shall be implemented.

**Comment by bmalinowsky** [comment]
That's what i thought wrt the additional column: for most of the day, people might just shrink its width because the content is the same, but one can also easily use it to look at days in isolation.

(thanks for the link to cfg4j, didn't know it :)

**Comment by bmalinowsky** [comment]
I pushed a straight-forward implementation of configurable date/time columns. The app checks for an optional config file `.calimero-gui.config`. Because of the quite flexible DTF patterns, the date/time distinction is actually not enforced in any way, any valid pattern should be good to go.

Any feedback welcome!

The config I tried looks like this:

```
# Date/time formats are according https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

## Date format for network & group monitor
# default
monitor.dateFormat=yyyy-MM-dd

## Time format for network & group monitor
# default
#monitor.timeFormat=HH:mm:ss.SSS
# time with zone offset
monitor.timeFormat=HH:mm:ss.SSSx
```

**Comment by daFritz84** [comment]
Works as advertised :+1: Big Thanks for that.

Just one remark: I noticed that you went for a 'self-brewed approach' for storing configuration into files. While this is sufficient for now, it seems not very scalable for future extensions. I also see why someone might not want to go for a full blown framework like cfg4j. But what about the [Java Properties Class](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html)? This looks like it would save us from the tedious String parsing. As far as I can see you don't even have to change the file format. (See this [Tutorial](http://www.codejava.net/coding/reading-and-writing-configuration-for-java-application-using-properties-class))

PS: As far as future extension goes: I'm thinking of storing/loading connection profiles. But this is something I want to try myself and submit a pull request later on.

**Comment by bmalinowsky** [comment]
Me not using Properties is just old habit: early versions did not handle non-latin strings well. (Could've used it of course.)

I leave the decision of a better config setup to any future feature which requires some elaborate data formats or complex file layout etc.
