### ISSUE TITLE
Run As Standalone Application Issue

### ISSUE THREAD

**Issue by Giesbern** [calimero-project/calimero-gui#4]
Hi,

I tried run calimero-gui on macOS Ventura but without success. There is some issue with SWT library mismatch. I've received log as below and restart the application doesn't solve problem.

./calimero-gui
SWT library mismatch, version 4956, platform cocoa
22:38:49:363 WARN swt-checker - No loadable SWT library on classpath (maybe first start?), trying to download SWT ...
22:38:49:363 INFO swt-checker - Architecture 64
22:38:49:364 INFO swt-checker - Detected OS: MacOS
22:38:49:369 INFO swt-checker - Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.swt.cocoa.macosx.x86_64/3.122.0/org.eclipse.swt.cocoa.macosx.x86_64-3.122.0.jar
22:38:49:776 INFO swt-checker - Saved to /Users/krzysztof/github/calimero-gui/build/distributions/calimero-gui-3.0-SNAPSHOT-20230306/lib/swt.jar
22:38:49:776 INFO swt-checker - Success, please restart the application!
krzysztof@MacBook-Pro-Krzysztof bin % ./calimero-gui
SWT library mismatch, version 4956, platform cocoa
22:41:30:589 WARN swt-checker - No loadable SWT library on classpath (maybe first start?), trying to download SWT ...
22:41:30:589 INFO swt-checker - Architecture 64
22:41:30:589 INFO swt-checker - Detected OS: MacOS
22:41:30:595 INFO swt-checker - Download https://repo.maven.apache.org/maven2/org/eclipse/platform/org.eclipse.swt.cocoa.macosx.x86_64/3.122.0/org.eclipse.swt.cocoa.macosx.x86_64-3.122.0.jar
22:41:30:996 INFO swt-checker - Saved to /Users/krzysztof/github/calimero-gui/build/distributions/calimero-gui-3.0-SNAPSHOT-20230306/lib/swt.jar
22:41:30:997 INFO swt-checker - Success, please restart the application!

Kind Regards,
Krzysztof

**Comment by bmalinowsky** [comment]
I think the reason is that you are running on an AArch64 MacBook, which was not detected by the downloader. I pushed a commit that added support for that architecture. Please try it out.

**Comment by Giesbern** [comment]
Thanks for the fast reply and added support for AArch64 MacBook. Everything works.
